vogar: code to work from an Android build tree, fall back to an SDK on the path, and report an error if we find neither. (Issue 1.) The build tree part is untested.
git-svn-id: http://vogar.googlecode.com/svn/trunk@13 aa685c63-decc-881d-cd2b-7fa72aad72e1

diff --git a/vogar b/vogar
--- a/vogar
+++ b/vogar
@@ -1,14 +1,27 @@
 #!/bin/bash
 
-adb_path=`which adb`
-android_tools_dir=`dirname ${adb_path}`
-android_platforms_dir=${android_tools_dir}/../platforms
-latest_android_platform=`ls -1 ${android_platforms_dir} | sort -n | tail -1`
-android_platform_dir=${android_platforms_dir}/${latest_android_platform}
+if [ -n "${ANDROID_BUILD_TOP}" ]; then
+    # We're in an Android build tree, so pull the latest sdk from there.
+    android_sdks_dir=${ANDROID_BUILD_TOP}/prebuilt/sdk/
+    latest_android_sdk=`ls -1 ${android_sdks_dir} | sort -n | tail -1`
+    android_platform_dir=${latest_android_sdk}
+else
+    # See if there's an Android SDK on the path.
+    adb_path=`which adb`
+    android_tools_dir=`dirname ${adb_path}`
+    android_platforms_dir=${android_tools_dir}/../platforms
+    latest_android_platform=`ls -1 ${android_platforms_dir} | sort -n | tail -1`
+    android_platform_dir=${android_platforms_dir}/${latest_android_platform}
+fi
+
+if [ ! -d "${android_platform_dir}" ]; then
+    echo "vogar: error: couldn't find an SDK on the path, and don't appear to be in an Android build tree"
+    exit 1
+fi
 
 vogar_jar=`dirname $0`/build/vogar.jar
-if [ ! -f ${vogar_jar} ]; then
-    echo "Couldn't find ${vogar_jar}; building ..."
+if [ ! -f "${vogar_jar}" ]; then
+    echo "vogar: info: couldn't find prebuilt ${vogar_jar}; building ..."
     ant -Dandroid.platform.dir=${android_platform_dir} jar
 fi
 
